---
title: "Rules Viz"
author: "Adam Ribaudo"
date: "3/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# https://cran.r-project.org/web/packages/arulesViz/vignettes/arulesViz.pdf

library(arules)
library(tidyverse)
library(data.table)
library(readxl)
library(knitr)
library(arulesViz)

df <- read_excel("..\\data\\online_retail_II.xlsx") %>%
  rename(InvoiceNo = Invoice, UnitPrice = Price, CustomerID = `Customer ID`) %>%
  mutate(isRefund = grepl("C", InvoiceNo) | Quantity < 0) %>%
  # Convert datetime to date
  mutate(InvoiceDate = as.Date(InvoiceDate, format = "%m/%d/%Y %H:%M")) %>%
  # Extract month
  mutate(InvoiceYearMonth = paste0(year(InvoiceDate),month(InvoiceDate))) %>%
  # Consider 2010 data only
  filter(grepl("2010",InvoiceYearMonth))

item_col <- "Description"
transaction_col <- "InvoiceNo"
time_col <- "InvoiceYearMonth"

# Break dataframe up into months and generate list of transaction tables for each month
get_transactions <- function(x){
  as(split(as.data.frame(x)[,item_col],as.data.frame(x)[,transaction_col]), "transactions")
}

transactions_union <- get_transactions(df)
# Transactions by time period
transactions <- lapply(split(df,f=df[time_col]),get_transactions)
time_periods <- length(transactions)

```



```{r warning=FALSE,message=FALSE}
minsup <- .005
minconf <- .5
plot(apriori(transactions_union, parameter = list(support = minsup, confidence = minconf), control=list(verbose=F)))
```


```{r warning=F,message=F}
minsup <- .01
minconf <- .5
rules <- apriori(transactions_union, parameter = list(support = minsup, confidence = minconf), control=list(verbose=F))
plot(rules, method = "matrix", measure = "lift")

```

Jaccard Distance: Distance metric for itemsets: number of items in common between X and Y divided by number of items in the union of X and Y 

```{r warning=F,message=F}
minsup <- .015
minconf <- .4
rules <- apriori(transactions_union, parameter = list(support = minsup, confidence = minconf), control=list(verbose=F))
# k means clustering on columns based on interest measure (lift)
#plot(rules, method = "grouped")
plot(rules, method = "grouped", control = list(k = 3, verbose=F))
```

```{r warning=F,message=F}
minsup <- .015
minconf <- .7
rules <- apriori(transactions_union, parameter = list(support = minsup, confidence = minconf), control=list(verbose=F))
#plot(rules, method = "grouped", control = list(k = 3, verbose=F))
rules_subset <- head(rules, n=5, by="lift")

# Use yEd grpah editor for editing. Remember 'parameter mapping' to map the custom params to visible params
# https://yed.yworks.com/support/manual/properties_mapper.html
#saveAsGraph(head(rules_subset, n = 1000, by = "lift"), file = "rules.graphml")
plot(rules_subset, method="graph")
```